# Generated by Django 4.2.29 on 2026-04-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_window', models.CharField(choices=[('morning', 'Morning (6am–12pm)'), ('afternoon', 'Afternoon (12pm–6pm)'), ('evening', 'Evening (6pm–12am)'), ('none', 'Not set')], default='none', max_length=20)),
                ('ai_tone', models.CharField(choices=[('warm', 'Warm & empathetic'), ('direct', 'Direct & concise'), ('playful', 'Playful')], default='warm', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
