# Generated by Django 4.2.29 on 2026-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_completed_at_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cognitive_load',
            field=models.CharField(choices=[('deep', 'Deep focus'), ('medium', 'Medium'), ('light', 'Light')], default='medium', max_length=10),
        ),
    ]
